export { default as EditProfile } from "./edit-profile/EditProfile";
export { default as Home } from "./home/Home";
export { default as Layout } from "./layout/Layout";
export { default as NewProperty } from "./new-property/NewProperty";
export { default as Login } from "./login/Login";
export { default as Properties } from "./properties/Properties";
export { default as Property } from "./property/Property";
export { default as Profile } from "./profile/Profile";
export { default as Signup } from "./signup/Signup";
